name: Deploy GCR
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  PROJECT_ID: ${{ secrets.GLOBAL_PROJECT_ID }}
  RUN_REGION: ${{ secrets.GLOBAL_RUN_REGION }}
  REPO_NAME: ${{ github.event.repository.name }}
  REPO_OWNER: ${{ github.event.repository.owner.login }}
  SA: ${{ secrets.GLOBAL_SA_KEY }}

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: nelonoel/branch-name@v1.0.1
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ env.SA }}
