name: Deploy GCR
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  REPO_NAME: ${{ github.event.repository.name }}
  REPO_OWNER: ${{ github.event.repository.owner.login }}
  SA: ${{ secrets.SA }}
  PROJECT_ID: laris-co-playground
  RUN_REGION: asia-southeast1

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: nelonoel/branch-name@v1.0.1
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ env.SA }}
      - run: gcloud auth configure-docker
      - name: Local Build
        run: docker build -t "asia.gcr.io/$PROJECT_ID/$REPO_NAME:${GITHUB_RUN_NUMBER}" .
      - run: docker push "asia.gcr.io/$PROJECT_ID/$REPO_NAME:${GITHUB_RUN_NUMBER}"
      - run: |
          gcloud run deploy $BRANCH_NAME-$REPO_NAME \
          --quiet \
          --region $RUN_REGION \
          --image asia.gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_RUN_NUMBER \
          --platform managed \
          --allow-unauthenticated
